# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore Logic
      run: dotnet restore /home/runner/work/GalleryManager/Logic/Logic.csproj
    - name: Restore DataAccess
      run: dotnet restore /home/runner/work/GalleryManager/DataAccess/DataAccess.csproj
    - name: Restore Interface
      run: dotnet restore /home/runner/work/GalleryManager/Interface/Interface.csproj
    - name: Restore UnitTests
      run: dotnet restore /home/runner/work/GalleryManager/UnitTests/UnitTests.csproj
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
